spring:
  cache:
   ehcache:
    config: classpath:ehcache.xml

server:
  port: 0
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ConnectTimeout:  10000
  ReadTimeout:  10000

api:
  root: https://api.meetup.com
  token: 221a6adea7a10f1d293a97ce02eeee95
  rate-limit: 4

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
